import { openingDate, closeingDate } from "./components/date/Date";
const Data = [
  {
    id: 1,
    name: "InstaCart",
    area: "Thane",
    category: "Grocery",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 2,
    name: "Beef Buddy",
    area: "Thane",
    category: "Butcher",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 3,
    name: "Dunzo",
    area: "Pune",
    category: "Grocery",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 4,
    name: "Easy Beef",
    area: "Pune",
    category: "Butcher",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 5,
    name: "Bakingo",
    area: "Mumbai Suburaban",
    category: "Baker",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 6,
    name: "Omnicare",
    area: "Mumbai Suburaban",
    category: "Chemist",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 7,
    name: "Bakery & co",
    area: "Nashik",
    category: "Baker",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 8,
    name: "Omnicare",
    area: "Nagpur",
    category: "Chemist",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 9,
    name: "Space Stationary",
    area: "Ahmednagar",
    category: "Stationary shop",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 10,
    name: "pen People",
    area: "Solapur",
    category: "Stationary shop",
    opening: openingDate,
    closeing: closeingDate,
  },
  {
    id: 11,
    name: "Paper Street",
    area: "Solapur",
    category: "Stationary shop",
    opening: openingDate,
    closeing: closeingDate,
  },
];
export default Data;
